#!/usr/bin/env bash
#  Install nginx web server
sudo apt-get -y update
sudo apt-get install -y nginx

mkdir /etc/nginx/html

sudo chown -R $USER:$USER /etc/nginx/html

echo "Hello World!" > /etc/nginx/html/index.html

echo "server {
        listen 80;
        listen [::]:80;

        root /etc/nginx/html
		index index.html index.htm index.nginx-debian.html;

        server_name _;
}" > /etc/nginx/sites-available/defult

sudo nginx -s restart
