#!/usr/bin/env bash
#  Install nginx web server
sudo apt-get -y update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo service nginx start
