#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
new_str="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUl\
	wu4 permanent;"
sudo sed -i "42i $new_str" /etc/nginx/sites-available/default
sudo service nginx start
sudo nginx -s reload
