#!/usr/bin/env bash
# Double the number of webservers

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

host=$HOSTNAME
new_str="\\\tadd_header X-Served-By $host;"
sudo sed -i "36i $new_str" /etc/nginx/sites-available/default

sudo service nginx restart
