#!/usr/bin/env bash
# install loadbalanacer

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo "
     frontend my_site
     	      bind *:80
	      mode http
	      option forwardfor
	      default_backend my_servers

     backend my_servers
     	     balance roundrobin
	     option httpchk
             server 392110-web-01 54.196.48.32 check
             server 392110-web-02 34.229.255.108 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
