#!/usr/bin/env bash
# displays the content of the file /etc/passwd.

file=/etc/passwd

while read -r line
do
	user=$(echo "$line" | cut -d: -f1)
	id=$(echo "$line" | cut -d: -f3)
	HD=$(echo "$line" | cut -d: -f6)
	echo "$user:$id:$HD"
done < $file
