#!usr/bin/env bash
#install ufw with some rules setup

sudo apt-get -y update
sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable 
